import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Medical Consultation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <div>
      <h1>Welcome to Medical Consultation</h1>
      <Link href="/login">Login</Link>
      </div>
    </>
  );
}
